# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
  # MySQL container
  mysql:
    # Use mysql:8.0.19 image
    image: mysql:5.7
    environment:
      - TZ: Asia/Taipei
    volumes:
       - ./mysql:/etc/mysql/
       - ./mydb:/var/lib/mysql
    #  - ./conf.d:/etc/mysql/conf.d/
       - ./opt:/opt
    ports:
      - "8094:3306"
    command:
      --max_allowed_packet=1000M
      --sql-mode=NO_AUTO_VALUE_ON_ZERO
    # Connect to "my-network" network, as defined below
    networks:
      - test-bb-network
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: root
  # phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    # Connect to "my-network" network, as defined below
    networks:
      - test-bb-network
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8095:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 1600M
    # Wait for "mysql" container to start first
    depends_on:
      - mysql

# Define networks
networks:
  test-bb-network:

